### PR TITLE
Jas glimnet repo

### PR DESCRIPTION
**Pull request by JazGlimnet**

### CODE REVIEW

**Review by frozenbanana — CHANGES_REQUESTED** [review]
I cannot see if you have added your gallery link to the root `index.html`. Please push again with it.

**Comment by frozenbanana** [comment]
Also, you have two Pull Request open but it is the same change. Only use one and apply your changes to the same branch.

**Review by JazGlimnet — COMMENTED** [review]
changed

**Comment by JazGlimnet** [comment]
made changes

**Pull request closed without merging**
